---
title: 'Calum Crawford'
baseURL: 'https://calumcrawford.com'
relativeURLs: true
enableRobotsTXT: true

theme: 'hugo-coder'

language: 'en'
languageCode: 'en-GB'

# permalinks:
# projects: 'projects/:slug/'
#   fixed: ':title/'
#   posts: 'posts/:slug/'

---
