---
# goldmark:
#   renderer:
#     unsafe: true
highlight:
  hl_Lines: ""
  lineAnchors: ""
  lineNoStart: 1
  lineNos: true
  lineNumbersInTable: false
  noClasses: true
  style: "dracula"
  tabWidth: 4
---
