---
author: 'Calum Crawford'
email: 'hi@calumcrawford.com'
description: "Calum Crawford's personal site."
avatarURL: '/images/avatar.jpg'

favicon_16: '/favicons/favicon-16x16.png'
favicon_32: '/favicons/favicon-32x32.png'
touchicon: '/favicons/apple-touch-icon.png'

# CONTENT & DATE FORMATTING
dateFormat: '2006-01-02'

# FOOTER
since: 2018
hideFooter: false
hideCredits: true
hideCopyright: true
commit: 'https://github.com/14zombies/calumcrawford.com/tree/'

# DISPLAY
## Custom CSS file must go in static/
#customCSS:
#    - css/custom.css

colorScheme: 'auto'
hideColorSchemeToggle: true

# Series see also post count
maxSeeAlsoItems: 5

# Social icons for home page, see https://fontawesome.com/icons?d=gallery&p=1
social:
  - name: 'email'
    icon: 'fa fa-envelope fa-2x'
    weight: 1
    url: 'mailto:hi@calumcrawford.com'

  - name: 'Github'
    icon: 'fa fa-github fa-2x'
    weight: 2
    url: 'https://github.com/14zombies'
  
  # - name: 'Gists'
  #   icon: 'fa fa-github fa-2x'
  #   weight: 3
  #   url: 'https://gist.github.com/14zombies'

  - name: 'Mastodon'
    icon: 'fa fa-mastodon fa-2x'
    weight: 4
    url: 'https://mastodon.social/@14zombies'

  - name: 'RSS'
    icon: 'fa fa-rss fa-2x'
    weight: 5
    url: '/index.xml'
    rel: 'alternate'
    type: 'application/rss+xml'
# csp:
#   childsrc:
#     - 'self'
#   fontsrc:
#     - 'self'
#     # 'https://fonts.gstatic.com',
#     # 'https://cdn.jsdelivr.net/'
#   formaction:
#     - 'self'
#   framesrc:
#     - 'self'
#   imgsrc:
#     - 'self'
#   objectsrc:
#     - 'none'
#   stylesrc:
#     - 'self'
#     - 'unsafe-inline'
#     # 'https://fonts.googleapis.com/',
#     # 'https://cdn.jsdelivr.net/'
#
#   scriptsrc:
#     - 'self'
#     - 'unsafe-inline'
#   prefetchsrc:
#     - 'self'
---