---
##
# domain: &domain https://calumcrawford.com
# hugo_version: &hugo_version 0.121.0
# nginx_tag: &nginx_tag 1.25-alpine
## 
kind: pipeline
type: docker
name: main

steps:
- name: Clone submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: Docker image build & push
  image: plugins/docker
  settings:
    registry: git.14zombies.com
    username:
      from_secret: username
    password:
        from_secret: password
    repo: git.14zombies.com/cal/calumcrawford.com
    tags: 
      - latest
      - ${DRONE_TAG##v}
    build_args:
      - NGINX_TAG=1.25-alpine
      - HUGO_VERSION=0.121.0

- name: Deploy
  image: plugins/webhook
  settings:
    urls:
      from_secret: hook

trigger:
  event:
    - tag

---
kind: signature
hmac: a17ffa3844f2bc70a227a287b16aca37b9666042f210707f157e57d8a95c2aea

...
