---
####
#
# BUILD AMD64 IMAGE
#
####
kind: pipeline
type: docker
name: build linux-amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: submodule
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: Docker image build & push (linux-amd64)
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      registry: git.14zombies.com
      username:
        from_secret: username
      password:
        from_secret: password
      repo: git.14zombies.com/cal/calumcrawford.com
      auto_tag: true
      auto_tag_suffix: linux-amd64
      build_args:
        - DOMAIN=https://calumcrawford.com
        - HUGO_VERSION=0.122.0
        - HUGO_ARCH=linux-amd64
      platforms:
        - linux/amd64
trigger:
  event:
    - tag
    - push
---
####
#
# BUILD ARM64 IMAGE
#
####
kind: pipeline
type: docker
name: build linux-arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: submodule
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: Docker image build & push (linux-arm64)
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      registry: git.14zombies.com
      username:
        from_secret: username
      password:
        from_secret: password
      repo: git.14zombies.com/cal/calumcrawford.com
      auto_tag: true
      auto_tag_suffix: linux-arm64
      build_args:
        - DOMAIN=https://calumcrawford.com
        - HUGO_VERSION=0.122.0
        - HUGO_ARCH=linux-arm64
      platforms:
        - linux/arm64
trigger:
  event:
    - tag
    - push
---
####
#
# BUILD MANIFEST
#
####
kind: pipeline
type: docker
name: manifest
steps:
  - name: manifest
    image: plugins/manifest
    settings:
      spec: docker/manifest.tmpl
      ignore_missing: true
      registry: git.14zombies.com
      password:
        from_secret: password
      username:
        from_secret: username
depends_on:
  - build linux-amd64
  - build linux-arm64
---
####
#
# DEPLOY TAGGED IMAGE
#
####
kind: pipeline
type: docker
name: Deploy
clone:
  disable: true
steps:
  - name: deploy – webhook
    image: plugins/webhook
    settings:
      urls:
        from_secret: hook
depends_on:
  - build linux-amd64
  - build linux-arm64
trigger:
  event:
    - push
    - tag
---
####
#
# DEPLOY DEV IMAGE
#
####
kind: pipeline
type: docker
name: Deploy – dev.calumcrawford.com
clone:
  disable: true
steps:
  - name: deploy – webhook
    image: plugins/webhook
    settings:
      urls:
        from_secret: dev_hook
depends_on:
  - build linux-amd64
  - build linux-arm64
trigger:
  event:
    - push
    - tag
---
####
#
# GITEA RELEASE
#
####
kind: pipeline
name: Gitea Release
type: docker
steps:
  - name: submodule
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: hugo build
    image: plugins/hugo
    settings:
      hugo_version: 0.122.0
      url: https://calumcrawford.com
  - name: build tar
    image: alpine/git
    commands:
      - tar czf ${DRONE_TAG}.tar.gz public/*
  - name: gitea release
    image: plugins/gitea-release
    settings:
      base_url: https://git.14zombies.com
      api_key:
        from_secret: release_token
      files: ${DRONE_TAG}.tar.gz
      checksum:
        - sha256
trigger:
  event:
    - tag
---
kind: signature
hmac: 4a520785b2e6ef532f3e26d44d8d5c7cb9914771f1dc559ed6f99c59e4950805

...
