---
title: 'Calum Crawford'
baseURL: 'https://calumcrawford.com'
relativeURLs: true
enableRobotsTXT: true

theme: hugo-coder

languageCode: en-GB
language: en

pygmentsCodefences: true
pygmentsUseClasses: true

permalinks:
  fixed: ':title/'
  posts: 'posts/:slug/'

params:
  author: 'Calum Crawford'
  description: ''
  avatarURL: 'img/avatar.jpg'
  #gravatar: 'c@calumcrawford.com'

  favicon_16: /img/favicon-16x16.png
  favicon_32: /img/favicon-32x32.png
  touchicon: /img/apple-touch-icon.png

# CONTENT & DATE FORMATTING
  justifyContent: false  # Set 'text-align: justify' to `.content`.
  dateform: '2006-01-02'
  dateformShort: '01-02'
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04 -0700'

# FOOTER
  since: 2018
  hideFooter: false
  hideCredits: true
  
  colorScheme: 'auto'
  hideColorSchemeToggle: true
  
  # Series see also post count
  maxSeeAlsoItems: 5

  taxonomies:
    category: 'categories'
    series: 'series'
    tag: 'tags'
    author: 'authors'

#Social icons for home page, see https://fontawesome.com/icons?d=gallery&p=1
  social:
    - name: 'email'
      icon: 'fa fa-envelope fa-2x'
      weight: 1
      url: 'mailto:hi@calumcrawford.com'

    - name: 'Github'
      icon: 'fa fa-github fa-2x'
      weight: 2
      url: 'https://github.com/14zombies'
    
    # - name: 'Gists'
    #   icon: 'fa fa-github fa-2x'
    #   weight: 3
    #   url: 'https://gist.github.com/14zombies'

    - name: 'Twitter'
      icon: 'fa fa-twitter fa-2x'
      weight: 4
      url: 'https://twitter.com/14zombies'

    - name: 'RSS'
      icon: 'fa fa-rss fa-2x'
      weight: 5
      url: 'https://calumcrawford.com/index.xml'
      rel: 'alternate'
      type: 'application/rss+xml'
---