name: Build & Push Container

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true

      - name: Hugo Build
        run: hugo --minify
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the tagged & latest Docker image
        run: docker build . -f Dockerfile -t ghcr.io/${{ github.repository }}:${{ github.sha }} -t ghcr.io/${{ github.repository }}:latest
      - name: Push the tagged Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Push the latest Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
